### ISSUE TITLE
Pruebas unitarias - Script Python

### ISSUE THREAD

**Issue by dvilla88** [dapivei/data-product-architecture-final-project#33]
Realizar pruebas unitarias para los niveles:
- [x] Clean
- [x] Feature 

Notas:
+ Ocupar MARBLES y que cada nivel tenga 2 pruebas unitarias. (Revisar implementacion de MARBLES, documentar errores,  clean y  Feature)
+ Solo considerar que para feature engeering hagamos uno con PANDAS. (Seccion particular de pandas para hacer unit testing)
+ Sugiero que se "active" el pipeline de unit testing a través de un parámetro de luigi --unit-testing True (Pensemoslo como otro DAG)
+ Agregar una tabla de metadatos para unit testing.

**Comment by dapivei** [comment]
**Tarea culminada**: se implementó el código base para los unittest correspondientes, revisar [tests](https://github.com/dapivei/data-product-architecture-final-project/tree/master/tests).
