### ISSUE TITLE
Input Aequitas - Dar formato a información de predicción.

### ISSUE THREAD

**Issue by dvilla88** [dapivei/data-product-architecture-final-project#36]
Dar formato a la información para que aequitas pueda leerla.

Notas:
La idea seria buscar en S3 los pickles de modelos que se han ejecutado para generar predicciones y a estas predicciones darles el formato correcto para correr aequitas. (Output CSV)

**Comment by dvilla88** [comment]
atributo protegido
metricas que vamos a medir en aequitas (definirlas de acuerdo a nuestro problema)
grupo de referencia

**Comment by dapivei** [comment]
JP ya actualizó el input del modelo con la inclusión de la variable borough; ya podemos correr uno o dos modelos con esos datos para preprocesar la información y evaluar el fairness y bias.

**Comment by dapivei** [comment]
Concluido!
