### ISSUE TITLE
Linaje de datos - Guardar metadatos en RDS de pruebas unitarias

### ISSUE THREAD

**Issue by dvilla88** [dapivei/data-product-architecture-final-project#37]
- [ ] Generar metadatos 
- [ ] Crear tablas para los schemas Clean y Feature
- [ ] Insertar metadatos en RDS

**Comment by dapivei** [comment]
Para unittest que truena: 
+  se muestra el contexto del error (marbles)
+ Se guarda metadata de la prueba, al menos: estatus, qué prueba se corrió, cuándo se ejecutó, mensaje de error (contexto)
Para unittest que corre sin error:
  + Se guarda metadata de la prueba, al menos: estatus, qué prueba se corrió, cuándo se ejecutó.
